CREATE DATABASE IF NOT EXISTS appDB;
CREATE USER IF NOT EXISTS 'user'@'%' IDENTIFIED BY 'password';
GRANT SELECT,UPDATE,INSERT,DELETE ON appDB.* TO 'user'@'%';
FLUSH PRIVILEGES;

USE appDB;
CREATE TABLE IF NOT EXISTS users (
  ID INT(11) NOT NULL AUTO_INCREMENT,
  login VARCHAR(20) NOT NULL,
  password VARCHAR(40) NOT NULL,
  PRIMARY KEY (ID)
);
CREATE TABLE IF NOT EXISTS magazines (
  ID INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(20) NOT NULL,
  price INTEGER,
  PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS books (
  ID INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(20) NOT NULL,
  price INTEGER,
  PRIMARY KEY (ID)
);

INSERT INTO magazines (name, price)
SELECT * FROM (SELECT 'Bamper', 5000) AS tmp
WHERE NOT EXISTS (
    SELECT name FROM magazines WHERE name = 'Bamper' AND price = 5000
) LIMIT 1;

INSERT INTO books (name, price)
SELECT * FROM (SELECT 'BMW E30', 500000) AS tmp
WHERE NOT EXISTS (
    SELECT name FROM books WHERE name = 'BMW E30' AND price = 500000
) LIMIT 1;

