CREATE DATABASE IF NOT EXISTS appDB;
CREATE USER IF NOT EXISTS 'user'@'%' IDENTIFIED BY 'password';
GRANT SELECT,UPDATE,INSERT,DELETE ON appDB.* TO 'user'@'%';
FLUSH PRIVILEGES;

USE appDB;
CREATE TABLE IF NOT EXISTS users (
  ID INT(11) NOT NULL AUTO_INCREMENT,
  login VARCHAR(20) NOT NULL,
  password VARCHAR(40) NOT NULL,
  PRIMARY KEY (ID)
);
CREATE TABLE IF NOT EXISTS books (
  ID INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(20) NOT NULL,
  price INTEGER,
  PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS magazines (
  ID INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(20) NOT NULL,
  price INTEGER,
  PRIMARY KEY (ID)
);

INSERT INTO books (name, price)
SELECT * FROM (SELECT 'Var and Peace', 1200) AS tmp
WHERE NOT EXISTS (
    SELECT name FROM books WHERE name = 'Var and Peace' AND price = 1200
) LIMIT 1;

INSERT INTO magazines (name, price)
SELECT * FROM (SELECT 'VOGUE', 1500) AS tmp
WHERE NOT EXISTS (
    SELECT name FROM magazines WHERE name = 'VOGUE' AND price = 1500
) LIMIT 1;

